"""Domain models for algorithmic alpha leads.

An AlphaLead represents an actionable trading signal generated by
the custom 5-signal scoring engine from real-time news events.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from uuid import uuid4


class LeadAction(str, Enum):
    """Discrete action recommendation for a lead."""

    BUY = "buy"
    SELL = "sell"
    ACCUMULATE = "accumulate"
    EXIT = "exit"


@dataclass
class AlphaLead:
    """A single algorithmically generated trading lead.

    Created by LeadService when the composite conviction score
    crosses the configured threshold.
    """

    ticker: str
    company_name: str
    action: LeadAction
    conviction: float          # 0.0 → 1.0 composite score
    expected_move_pct: float   # signed expected % move

    trigger_event_id: str
    trigger_event_title: str

    reasoning: list[str] = field(default_factory=list)
    signals: dict[str, float] = field(default_factory=dict)

    sector: str = ""
    key_voice: str | None = None

    expires_at: datetime = field(
        default_factory=lambda: datetime.utcnow() + timedelta(hours=24)
    )
    timestamp: datetime = field(default_factory=datetime.utcnow)
    id: str = field(default_factory=lambda: str(uuid4()))

    @property
    def is_expired(self) -> bool:
        return datetime.utcnow() > self.expires_at

    @property
    def is_high_conviction(self) -> bool:
        return abs(self.conviction) >= 0.7
