"""Domain models for opportunity discovery."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from uuid import uuid4


class OpportunityOrder(str, Enum):
    """
    The causal distance from the triggering event.

    First-order: directly named in the event.
    Second-order: one hop away in the knowledge graph.
    Third-order: two hops away — the hidden alpha.
    """

    FIRST_ORDER = "first_order"
    SECOND_ORDER = "second_order"
    THIRD_ORDER = "third_order"


class OpportunityDirection(str, Enum):
    LONG = "long"     # Expected to benefit
    SHORT = "short"   # Expected to suffer


@dataclass
class Opportunity:
    """
    A discovered market opportunity generated by the Opportunity Scanner.

    Third-order opportunities are the most valuable — they represent
    relationships that most market participants have not yet priced in.
    """

    ticker: str
    company_name: str
    sector: str
    trigger_event_id: str
    trigger_event_title: str
    order: OpportunityOrder
    direction: OpportunityDirection
    reasoning: list[str] = field(default_factory=list)
    graph_path: list[str] = field(default_factory=list)  # node chain
    confidence: float = 0.0
    expected_impact_pct: float = 0.0

    id: str = field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def is_hidden_alpha(self) -> bool:
        """True for 3rd-order opportunities — the most overlooked."""
        return self.order == OpportunityOrder.THIRD_ORDER
