"""Domain models for the risk radar."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from uuid import uuid4


class RiskFactor(str, Enum):
    """The type of risk being flagged."""

    PROMOTER_SELLING = "promoter_selling"
    PROMOTER_PLEDGE_INCREASE = "promoter_pledge_increase"
    INSIDER_SELLING = "insider_selling"
    DEBT_SPIKE = "debt_spike"
    GOVERNANCE_ISSUE = "governance_issue"
    AUDITOR_RESIGNATION = "auditor_resignation"
    LEGAL_DISPUTE = "legal_dispute"
    SECTOR_DOWNTURN = "sector_downturn"
    MACRO_RISK = "macro_risk"
    FII_OUTFLOW = "fii_outflow"
    EARNINGS_MISS = "earnings_miss"
    GUIDANCE_DOWNGRADE = "guidance_downgrade"
    ANALYST_DOWNGRADE = "analyst_downgrade"


class RiskSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class RiskAlert:
    """
    A risk signal generated by the Risk Radar for a specific company.

    Severity is always computed dynamically from the magnitude of the
    triggering condition — it is never hardcoded.
    """

    ticker: str
    company_name: str
    factor: RiskFactor
    severity: RiskSeverity
    description: str
    supporting_evidence: list[str] = field(default_factory=list)
    source: str = ""

    id: str = field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def is_critical(self) -> bool:
        return self.severity == RiskSeverity.CRITICAL
