"""
Generic and domain-specific repository interfaces.

Repositories are the only gateway between the domain and the
persistence layer.  Services depend on these interfaces, never on
concrete SQLAlchemy models.
"""

from __future__ import annotations

from typing import Generic, Protocol, TypeVar

from app.domain.models.event import MarketEvent
from app.domain.models.ipo import IPO
from app.domain.models.portfolio import Holding
from app.domain.models.prediction import Prediction
from app.domain.models.risk import RiskAlert
from app.domain.models.stakeholder import (
    BulkDeal,
    InstitutionalFlow,
    InsiderTrade,
    ShareholdingPattern,
    SmartMoneySignal,
)

T = TypeVar("T")


class IRepository(Protocol[T]):
    """Generic CRUD repository interface."""

    async def save(self, entity: T) -> T:
        """Persist a new entity and return the saved version."""
        ...

    async def get_by_id(self, entity_id: str) -> T | None:
        ...

    async def delete(self, entity_id: str) -> bool:
        ...


class IEventRepository(Protocol):
    async def save(self, event: MarketEvent) -> MarketEvent: ...
    async def get_by_id(self, event_id: str) -> MarketEvent | None: ...
    async def get_recent(self, *, limit: int = 50) -> list[MarketEvent]: ...
    async def get_by_category(self, category: str, *, limit: int = 20) -> list[MarketEvent]: ...
    async def exists_by_hash(self, content_hash: str) -> bool: ...


class IPredictionRepository(Protocol):
    async def save(self, prediction: Prediction) -> Prediction: ...
    async def get_by_id(self, prediction_id: str) -> Prediction | None: ...
    async def get_for_ticker(self, ticker: str, *, limit: int = 10) -> list[Prediction]: ...
    async def get_unevaluated(self) -> list[Prediction]: ...
    async def update_outcome(self, prediction_id: str, actual_move_pct: float) -> None: ...


class IHoldingRepository(Protocol):
    async def save(self, holding: Holding) -> Holding: ...
    async def get_all(self) -> list[Holding]: ...
    async def get_by_ticker(self, ticker: str) -> Holding | None: ...
    async def delete(self, ticker: str) -> bool: ...


class IIPORepository(Protocol):
    async def save(self, ipo: IPO) -> IPO: ...
    async def get_all(self) -> list[IPO]: ...
    async def get_by_status(self, status: str) -> list[IPO]: ...
    async def get_by_id(self, ipo_id: str) -> IPO | None: ...
    async def delete(self, ipo_id: str) -> bool: ...


class IRiskAlertRepository(Protocol):
    async def save(self, alert: RiskAlert) -> RiskAlert: ...
    async def get_recent(self, *, limit: int = 50) -> list[RiskAlert]: ...
    async def get_for_ticker(self, ticker: str) -> list[RiskAlert]: ...


class IStakeholderRepository(Protocol):
    async def save_shareholding(self, pattern: ShareholdingPattern) -> ShareholdingPattern: ...
    async def get_shareholding(self, ticker: str) -> ShareholdingPattern | None: ...
    async def get_shareholding_history(self, ticker: str, *, quarters: int = 8) -> list[ShareholdingPattern]: ...
    async def save_bulk_deal(self, deal: BulkDeal) -> BulkDeal: ...
    async def get_bulk_deals(self, ticker: str | None, *, days: int = 30) -> list[BulkDeal]: ...
    async def save_insider_trade(self, trade: InsiderTrade) -> InsiderTrade: ...
    async def get_insider_trades(self, ticker: str | None, *, days: int = 90) -> list[InsiderTrade]: ...
    async def save_institutional_flow(self, flow: InstitutionalFlow) -> InstitutionalFlow: ...
    async def get_institutional_flows(self, *, days: int = 30) -> list[InstitutionalFlow]: ...
    async def save_smart_money_signal(self, signal: SmartMoneySignal) -> SmartMoneySignal: ...
    async def get_smart_money_signal(self, ticker: str) -> SmartMoneySignal | None: ...
